---
- name: Create bootstrap VM on KVM node1
  shell:
    cmd: >-
        virt-install
        -n bootstrap
        --description "Bootstrap Machine for Openshift 4 Cluster"
        --memory {{ vm_mem }}
        --vcpus={{ vm_cpu }}
        --os-variant=rhel9.0
        --os-type linux
        --noreboot
        --disk pool=ocp_vms,bus=virtio,size={{ vm_size }}
        --serial pty
        --console pty
        --pxe
        --network bridge:{{ common.interface_name }},mac.address={% for item in ocp_bootstrap %}{{ item.mac_address }}{% endfor %}
        --wait 10
  delegate_to: "{{ groups['kvm_nodes'][0] }}" 

- name: Restart bootstrap Domain
  shell: 
    cmd: >-
        virsh 
        --connect qemu:///system start bootstrap
  delegate_to: "{{ groups['kvm_nodes'][0] }}" 

- name: Create master1 VM on KVM node1
  shell:
    cmd: >-
        virt-install
        -n master1
        --description "Master1 Machine for Openshift 4 Cluster"
        --memory {{ vm_mem }}
        --vcpus={{ vm_cpu }}  
        --os-variant=rhel9.0
        --os-type linux
        --noreboot
        --disk pool=ocp_vms,bus=virtio,size={{ vm_size }}
        --serial pty 
        --console pty
        --pxe 
        --network bridge:{{ common.interface_name }},mac.address={{ ocp_masters[0].mac_address }}
        --wait 10
  delegate_to: "{{ groups['kvm_nodes'][0] }}" 

- name: Restart master1 Domain
  shell:
    cmd: >-
        virsh
        --connect qemu:///system start master1
  delegate_to: "{{ groups['kvm_nodes'][0] }}"

- name: Create Master2 VM on KVM node2
  shell:
    cmd: >-
        virt-install
        -n master2
        --description "Master2 Machine for Openshift 4 Cluster"
        --memory {{ vm_mem }}
        --vcpus={{ vm_cpu }}
        --os-variant=rhel9.0
        --os-type linux
        --noreboot
        --disk pool=ocp_vms,bus=virtio,size={{ vm_size }}
        --serial pty
        --console pty
        --pxe
        --network bridge:{{ common.interface_name }},mac.address={{ ocp_masters[1].mac_address }}
        --wait 10
  delegate_to: "{{ groups['kvm_nodes'][1] }}"

- name: Restart master2 Domain
  shell:
    cmd: >-
        virsh
        --connect qemu:///system start master2
  delegate_to: "{{ groups['kvm_nodes'][1] }}"

- name: Create Master3 VM on KVM node
  shell:
    cmd: >-
        virt-install
        -n  master3
        --description "Master3 Machine for Openshift 4 Cluster"
        --memory {{ vm_mem }}
        --vcpus={{ vm_cpu }}
        --os-variant=rhel9.0
        --os-type linux
        --noreboot
        --disk pool=ocp_vms,bus=virtio,size={{ vm_size }}
        --serial pty
        --console pty
        --pxe
        --network bridge:{{ common.interface_name }},mac.address={{ ocp_masters[2].mac_address }}
        --wait 10
  delegate_to: "{{ groups['kvm_nodes'][2] }}"

- name: Restart master3 Domain
  shell:
    cmd: >-
        virsh
        --connect qemu:///system start master3
  delegate_to: "{{ groups['kvm_nodes'][2] }}"



