###
## Copyright (2018) Hewlett Packard Enterprise Development LP
##
## Licensed under the Apache License, Version 2.0 (the "License");
## You may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##Â http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
#### 

---

- name: disable all repos
  command: "subscription-manager repos --disable='*'"

- name: enable RHEL7 Server repos
  command: "subscription-manager repos --enable=rhel-7-server-rpms"

- name: enabled RHEL 7 Server extras
  command: "subscription-manager repos --enable=rhel-7-server-extras-rpms"

- name: enable OSE 3.11 repos
  command: "subscription-manager repos --enable=rhel-7-server-ose-3.11-rpms"

- name: enable fast-datapath repo
  command: "subscription-manager repos --enable=rhel-7-fast-datapath-rpms"

- name: enable the Ansible repo
  command: "subscription-manager repos --enable=rhel-7-server-ansible-2.6-rpms"
