---
- name: Prepare rhel 7.9 Installer VM to add worker nodes
  hosts: rhel7_installerVM
  gather_facts: True
  vars_files:
    - ../input.yaml
  roles:
    - role: roles/prepare_installer_vm

