---

- import_tasks: dcbond.yaml
#- import_tasks: mgbond.yaml
#- import_tasks: iscsi.yaml
#- import_tasks: iqns.yaml
- import_tasks: services.yaml
- import_tasks: mpath.yaml
- import_tasks: detach.yaml
