###
## Copyright (2018) Hewlett Packard Enterprise Development LP
##
## Licensed under the Apache License, Version 2.0 (the "License");
## You may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##Â http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
####

---


- name: Disable PXE interface  
  lineinfile:
     path: /etc/sysconfig/network-scripts/ifcfg-ens3f0
     state: present
     regexp: '^ONBOOT=yes'
     line: 'ONBOOT=no'

- name: Disable Second PXE interface  
  lineinfile:
     path: /etc/sysconfig/network-scripts/ifcfg-ens3f1
     state: present
     regexp: '^ONBOOT=yes'
     line: 'ONBOOT=no'
  
#- name: start the primary bond
#  command: "nmcli con up '{{ bondname1 }}'"

- name: start the secondary bond
  command: "nmcli con up '{{ bondname2 }}'"

- name: start the iscsi a side adapter
  command: "nmcli con up '{{ iscsia }}'"

- name: start the iscsi b side adapter
  command: "nmcli con up '{{ iscsib }}'"


- name: restart the host
  command: /sbin/shutdown -r +1
  async: 0
  poll: 0
  ignore_errors: true

- name: Wait for host to boot up
  wait_for_connection:
    delay: 60
    timeout: 300

